FiX key extraction from RS485 interface (#165)
It's currently broken:

root@firewall:/opt/solaredge# ./semonitor.py -m -t 4 -c 12,H239 -s 7315977D /dev/ttyUSB0
Traceback (most recent call last):
  File "./semonitor.py", line 268, in <module>
    doCommands(args, mode, state, dataFile, recFile, outFile)
  File "./semonitor.py", line 175, in doCommands
    masterGrant(dataFile, recFile, args.slaves[0])
TypeError: masterGrant() missing 1 required positional argument: 'slaveAddr'

Co-authored-by: Ben Castricum <github@bencastricum.nl>